version: '3'

services:
  db:
    container_name: valotalk-project-data
    image: postgres:15.2-alpine
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: valotalk
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    container_name: valotalk-project-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/valotalk-project
    depends_on:
      - db

  nginx:
    container_name: valotalk-project-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/valotalk-project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

volumes:
  db_data: {}
